"""create GrammarStory table

Revision ID: 0bf1e6139c39
Revises: c0d4c4cfbcd2
Create Date: 2018-07-21 12:51:14.596985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bf1e6139c39'
down_revision = 'c0d4c4cfbcd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Integer(), nullable=True),
    sa.Column('sentence', sa.String(length=1000), nullable=True),
    sa.Column('crawler_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crawler_id'], ['crawler.id'], name=op.f('fk_grammar_story_crawler_id_crawler')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grammar_story'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grammar_story')
    # ### end Alembic commands ###
