"""change nullable False crawler_id from preprocess

Revision ID: 0eb89d824680
Revises: adcbcecbcfe9
Create Date: 2018-06-24 21:00:42.358676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb89d824680'
down_revision = 'adcbcecbcfe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preprocess', schema=None) as batch_op:
        batch_op.alter_column('crawler_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preprocess', schema=None) as batch_op:
        batch_op.alter_column('crawler_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
