"""table penentuan kelas

Revision ID: 90e072488a4a
Revises: 972e4299be5d
Create Date: 2018-07-10 14:16:31.460739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e072488a4a'
down_revision = '972e4299be5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penentuan_kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=True),
    sa.Column('function', sa.String(length=200), nullable=True),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('crawler_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crawler_id'], ['crawler.id'], name=op.f('fk_penentuan_kelas_crawler_id_crawler')),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweet.id'], name=op.f('fk_penentuan_kelas_tweet_id_tweet')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_penentuan_kelas'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('penentuan_kelas')
    # ### end Alembic commands ###
