"""attractions table

Revision ID: 9358474e7ae4
Revises: 89ea7c4ef46c
Create Date: 2018-10-21 10:26:36.559515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9358474e7ae4'
down_revision = '89ea7c4ef46c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attractions', sa.String(length=1000), nullable=True),
    sa.Column('crawler_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crawler_id'], ['crawler.id'], name=op.f('fk_attractions_crawler_id_crawler')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attractions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attractions')
    # ### end Alembic commands ###
