"""create table postag

Revision ID: 972e4299be5d
Revises: 0eb89d824680
Create Date: 2018-06-30 21:31:17.872697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972e4299be5d'
down_revision = '0eb89d824680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=True),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('crawler_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crawler_id'], ['crawler.id'], name=op.f('fk_postag_crawler_id_crawler')),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweet.id'], name=op.f('fk_postag_tweet_id_tweet')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_postag'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postag')
    # ### end Alembic commands ###
