"""add table ldapwz

Revision ID: c0d4c4cfbcd2
Revises: 90e072488a4a
Create Date: 2018-07-12 21:38:09.433969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d4c4cfbcd2'
down_revision = '90e072488a4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ldapwz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=200), nullable=True),
    sa.Column('topic', sa.Integer(), nullable=True),
    sa.Column('pwz', sa.String(length=200), nullable=True),
    sa.Column('crawler_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['crawler_id'], ['crawler.id'], name=op.f('fk_ldapwz_crawler_id_crawler')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ldapwz'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ldapwz')
    # ### end Alembic commands ###
